sudo: required
addons:
  chrome: stable
language: node_js
node_js:
    - '10'
cache:
  directories:
    - ~/.npm
    - node_modules
before_install:
    - sudo apt-get update
    - sudo apt-get install alsa-utils
    - sudo apt-get install avahi-utils
    - sudo reboot
install:
  - npm install
script: npm start && npm run cy:run
